requires 'Parallel::ForkManager';
requires 'Log::Log4perl';
requires 'FindBin';
requires 'IO::File';
requires 'File::Copy';
requires 'Role::Tiny';
requires 'Bio::SeqIO';
requires 'Bio::DB::Fasta';
requires 'File::Temp';
requires 'Bio::Seq';
requires 'File::Basename';
requires 'Tie::Log4perl';
requires 'Archive::Zip';
requires 'Test::Pretty';
requires 'Getopt::Long';
requires 'Digest::MD5'
